name: Build and Release

on:
  push:
    tags:
      - 'v*'  # v1.0 のようなタグを push したときに実行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Javaをセットアップ
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'  # 使用しているJavaバージョンに合わせて変更

      - name: Mavenでビルド
        run: mvn package --no-transfer-progress

      - name: リリースを作成
        uses: softprops/action-gh-release@v2
        with:
          files: target/*.jar  # JARのパスを指定
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
