name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set version
        id: set_version
        run: |
          git fetch --tags

          latest=$(git tag --sort=-v:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)
          if [ -z "$latest" ]; then
            latest="v0.9.9"  # ← ここを起点にして、次を v1.0.0 にします
          fi

          version="${latest#v}"
          IFS='.' read -r major minor patch <<< "$version"

          patch=$((patch + 1))
          if [ "$patch" -gt 9 ]; then
            patch=0
            minor=$((minor + 1))
          fi
          if [ "$minor" -gt 9 ]; then
            minor=0
            major=$((major + 1))
          fi

          next_tag="v$major.$minor.$patch"
          echo "NEXT_TAG=$next_tag" >> "$GITHUB_OUTPUT"

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: List target directory contents
        run: ls -lh target

      - name: Rename JAR
        run: |
          mkdir output
          cp target/minecraft-chat-translator-1.0.jar output/MCT-${{ steps.set_version.outputs.NEXT_TAG }}.jar

      - name: Create Release and Upload JAR
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.set_version.outputs.NEXT_TAG }}
          name: MCT ${{ steps.set_version.outputs.NEXT_TAG }}
          body: 初回リリース v1.0.0
           ローマ字から漢字に変換する機能を実装。
          files: output/MCT-${{ steps.set_version.outputs.NEXT_TAG }}.jar

      - name: Push tag to repository
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ steps.set_version.outputs.NEXT_TAG }}
          git push origin ${{ steps.set_version.outputs.NEXT_TAG }}
